create_alarm:
  name: Create Alarm
  description: Notifies Noonlight of an alarm with specific services.
  fields:
    service:
      name: Service
      description: Service that the alarm should call (police, fire, medical)
      required: true
      example: "police"
      default: "police"
      selector:
        select:
          options:
            - "police"
            - "fire"
            - "medical"
    instruction:
      name: Instruction
      description: Optional instructions or notes to include with the Noonlight alarm (e.g., "Intruder in the garage" or "Smoke in kitchen").
      required: false
      example: "Front door forced open, dog inside."
      selector:
        text:
          multiline: true
